/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC1155Errors__factory>;
    getContractFactory(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Errors__factory>;
    getContractFactory(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Errors__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SafeERC20__factory>;
    getContractFactory(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC721__factory>;
    getContractFactory(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Metadata__factory>;
    getContractFactory(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721__factory>;
    getContractFactory(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC721Receiver__factory>;
    getContractFactory(
      name: "Address",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Address__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "Math",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Math__factory>;
    getContractFactory(
      name: "Strings",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Strings__factory>;
    getContractFactory(
      name: "HasherBenchmarks",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HasherBenchmarks__factory>;
    getContractFactory(
      name: "Hasher",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Hasher__factory>;
    getContractFactory(
      name: "MockVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockVerifier__factory>;
    getContractFactory(
      name: "Pairing",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pairing__factory>;
    getContractFactory(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT3__factory>;
    getContractFactory(
      name: "PoseidonT4",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT4__factory>;
    getContractFactory(
      name: "PoseidonT5",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT5__factory>;
    getContractFactory(
      name: "PoseidonT6",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PoseidonT6__factory>;
    getContractFactory(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier__factory>;
    getContractFactory(
      name: "EASGatekeeper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EASGatekeeper__factory>;
    getContractFactory(
      name: "FreeForAllGatekeeper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FreeForAllGatekeeper__factory>;
    getContractFactory(
      name: "HatsGatekeeperBase",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HatsGatekeeperBase__factory>;
    getContractFactory(
      name: "HatsGatekeeperMultiple",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HatsGatekeeperMultiple__factory>;
    getContractFactory(
      name: "HatsGatekeeperSingle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.HatsGatekeeperSingle__factory>;
    getContractFactory(
      name: "SignUpGatekeeper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignUpGatekeeper__factory>;
    getContractFactory(
      name: "SignUpTokenGatekeeper",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignUpTokenGatekeeper__factory>;
    getContractFactory(
      name: "ConstantInitialVoiceCreditProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConstantInitialVoiceCreditProxy__factory>;
    getContractFactory(
      name: "InitialVoiceCreditProxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.InitialVoiceCreditProxy__factory>;
    getContractFactory(
      name: "IEAS",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IEAS__factory>;
    getContractFactory(
      name: "IHats",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IHats__factory>;
    getContractFactory(
      name: "IMACI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMACI__factory>;
    getContractFactory(
      name: "IMessageProcessor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMessageProcessor__factory>;
    getContractFactory(
      name: "IMessageProcessorFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMessageProcessorFactory__factory>;
    getContractFactory(
      name: "IPoll",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPoll__factory>;
    getContractFactory(
      name: "IPollFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPollFactory__factory>;
    getContractFactory(
      name: "ITallyFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITallyFactory__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "IVkRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVkRegistry__factory>;
    getContractFactory(
      name: "MACI",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MACI__factory>;
    getContractFactory(
      name: "MessageProcessor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MessageProcessor__factory>;
    getContractFactory(
      name: "MessageProcessorFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MessageProcessorFactory__factory>;
    getContractFactory(
      name: "MockHatsProtocol",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockHatsProtocol__factory>;
    getContractFactory(
      name: "Poll",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Poll__factory>;
    getContractFactory(
      name: "PollFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PollFactory__factory>;
    getContractFactory(
      name: "SignUpToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SignUpToken__factory>;
    getContractFactory(
      name: "Tally",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Tally__factory>;
    getContractFactory(
      name: "TallyFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TallyFactory__factory>;
    getContractFactory(
      name: "TopupCredit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TopupCredit__factory>;
    getContractFactory(
      name: "AccQueue",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueue__factory>;
    getContractFactory(
      name: "AccQueueBinary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueueBinary__factory>;
    getContractFactory(
      name: "AccQueueBinary0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueueBinary0__factory>;
    getContractFactory(
      name: "AccQueueBinaryMaci",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueueBinaryMaci__factory>;
    getContractFactory(
      name: "AccQueueQuinary",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueueQuinary__factory>;
    getContractFactory(
      name: "AccQueueQuinary0",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueueQuinary0__factory>;
    getContractFactory(
      name: "AccQueueQuinaryBlankSl",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueueQuinaryBlankSl__factory>;
    getContractFactory(
      name: "AccQueueQuinaryMaci",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AccQueueQuinaryMaci__factory>;
    getContractFactory(
      name: "CommonUtilities",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CommonUtilities__factory>;
    getContractFactory(
      name: "DomainObjs",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DomainObjs__factory>;
    getContractFactory(
      name: "Utilities",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Utilities__factory>;
    getContractFactory(
      name: "VkRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.VkRegistry__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "IERC1155Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC1155Errors>;
    getContractAt(
      name: "IERC20Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Errors>;
    getContractAt(
      name: "IERC721Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Errors>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "SafeERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SafeERC20>;
    getContractAt(
      name: "ERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC721>;
    getContractAt(
      name: "IERC721Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Metadata>;
    getContractAt(
      name: "IERC721",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721>;
    getContractAt(
      name: "IERC721Receiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC721Receiver>;
    getContractAt(
      name: "Address",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Address>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "Math",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Math>;
    getContractAt(
      name: "Strings",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Strings>;
    getContractAt(
      name: "HasherBenchmarks",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HasherBenchmarks>;
    getContractAt(
      name: "Hasher",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Hasher>;
    getContractAt(
      name: "MockVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockVerifier>;
    getContractAt(
      name: "Pairing",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pairing>;
    getContractAt(
      name: "PoseidonT3",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT3>;
    getContractAt(
      name: "PoseidonT4",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT4>;
    getContractAt(
      name: "PoseidonT5",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT5>;
    getContractAt(
      name: "PoseidonT6",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PoseidonT6>;
    getContractAt(
      name: "Verifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier>;
    getContractAt(
      name: "EASGatekeeper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.EASGatekeeper>;
    getContractAt(
      name: "FreeForAllGatekeeper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FreeForAllGatekeeper>;
    getContractAt(
      name: "HatsGatekeeperBase",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HatsGatekeeperBase>;
    getContractAt(
      name: "HatsGatekeeperMultiple",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HatsGatekeeperMultiple>;
    getContractAt(
      name: "HatsGatekeeperSingle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.HatsGatekeeperSingle>;
    getContractAt(
      name: "SignUpGatekeeper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SignUpGatekeeper>;
    getContractAt(
      name: "SignUpTokenGatekeeper",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SignUpTokenGatekeeper>;
    getContractAt(
      name: "ConstantInitialVoiceCreditProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ConstantInitialVoiceCreditProxy>;
    getContractAt(
      name: "InitialVoiceCreditProxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.InitialVoiceCreditProxy>;
    getContractAt(
      name: "IEAS",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IEAS>;
    getContractAt(
      name: "IHats",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IHats>;
    getContractAt(
      name: "IMACI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMACI>;
    getContractAt(
      name: "IMessageProcessor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMessageProcessor>;
    getContractAt(
      name: "IMessageProcessorFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMessageProcessorFactory>;
    getContractAt(
      name: "IPoll",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPoll>;
    getContractAt(
      name: "IPollFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPollFactory>;
    getContractAt(
      name: "ITallyFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITallyFactory>;
    getContractAt(
      name: "IVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "IVkRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVkRegistry>;
    getContractAt(
      name: "MACI",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MACI>;
    getContractAt(
      name: "MessageProcessor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MessageProcessor>;
    getContractAt(
      name: "MessageProcessorFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MessageProcessorFactory>;
    getContractAt(
      name: "MockHatsProtocol",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockHatsProtocol>;
    getContractAt(
      name: "Poll",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Poll>;
    getContractAt(
      name: "PollFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PollFactory>;
    getContractAt(
      name: "SignUpToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SignUpToken>;
    getContractAt(
      name: "Tally",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Tally>;
    getContractAt(
      name: "TallyFactory",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TallyFactory>;
    getContractAt(
      name: "TopupCredit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TopupCredit>;
    getContractAt(
      name: "AccQueue",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueue>;
    getContractAt(
      name: "AccQueueBinary",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueueBinary>;
    getContractAt(
      name: "AccQueueBinary0",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueueBinary0>;
    getContractAt(
      name: "AccQueueBinaryMaci",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueueBinaryMaci>;
    getContractAt(
      name: "AccQueueQuinary",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueueQuinary>;
    getContractAt(
      name: "AccQueueQuinary0",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueueQuinary0>;
    getContractAt(
      name: "AccQueueQuinaryBlankSl",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueueQuinaryBlankSl>;
    getContractAt(
      name: "AccQueueQuinaryMaci",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AccQueueQuinaryMaci>;
    getContractAt(
      name: "CommonUtilities",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CommonUtilities>;
    getContractAt(
      name: "DomainObjs",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DomainObjs>;
    getContractAt(
      name: "Utilities",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Utilities>;
    getContractAt(
      name: "VkRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.VkRegistry>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "ERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "Address",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Math",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Math>;
    deployContract(
      name: "Strings",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "HasherBenchmarks",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HasherBenchmarks>;
    deployContract(
      name: "Hasher",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Hasher>;
    deployContract(
      name: "MockVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockVerifier>;
    deployContract(
      name: "Pairing",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pairing>;
    deployContract(
      name: "PoseidonT3",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "PoseidonT4",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT4>;
    deployContract(
      name: "PoseidonT5",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT5>;
    deployContract(
      name: "PoseidonT6",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT6>;
    deployContract(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier>;
    deployContract(
      name: "EASGatekeeper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EASGatekeeper>;
    deployContract(
      name: "FreeForAllGatekeeper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FreeForAllGatekeeper>;
    deployContract(
      name: "HatsGatekeeperBase",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HatsGatekeeperBase>;
    deployContract(
      name: "HatsGatekeeperMultiple",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HatsGatekeeperMultiple>;
    deployContract(
      name: "HatsGatekeeperSingle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HatsGatekeeperSingle>;
    deployContract(
      name: "SignUpGatekeeper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignUpGatekeeper>;
    deployContract(
      name: "SignUpTokenGatekeeper",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignUpTokenGatekeeper>;
    deployContract(
      name: "ConstantInitialVoiceCreditProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConstantInitialVoiceCreditProxy>;
    deployContract(
      name: "InitialVoiceCreditProxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InitialVoiceCreditProxy>;
    deployContract(
      name: "IEAS",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEAS>;
    deployContract(
      name: "IHats",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHats>;
    deployContract(
      name: "IMACI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMACI>;
    deployContract(
      name: "IMessageProcessor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMessageProcessor>;
    deployContract(
      name: "IMessageProcessorFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMessageProcessorFactory>;
    deployContract(
      name: "IPoll",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPoll>;
    deployContract(
      name: "IPollFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPollFactory>;
    deployContract(
      name: "ITallyFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITallyFactory>;
    deployContract(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "IVkRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVkRegistry>;
    deployContract(
      name: "MACI",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MACI>;
    deployContract(
      name: "MessageProcessor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MessageProcessor>;
    deployContract(
      name: "MessageProcessorFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MessageProcessorFactory>;
    deployContract(
      name: "MockHatsProtocol",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHatsProtocol>;
    deployContract(
      name: "Poll",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Poll>;
    deployContract(
      name: "PollFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PollFactory>;
    deployContract(
      name: "SignUpToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignUpToken>;
    deployContract(
      name: "Tally",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Tally>;
    deployContract(
      name: "TallyFactory",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TallyFactory>;
    deployContract(
      name: "TopupCredit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TopupCredit>;
    deployContract(
      name: "AccQueue",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueue>;
    deployContract(
      name: "AccQueueBinary",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueBinary>;
    deployContract(
      name: "AccQueueBinary0",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueBinary0>;
    deployContract(
      name: "AccQueueBinaryMaci",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueBinaryMaci>;
    deployContract(
      name: "AccQueueQuinary",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinary>;
    deployContract(
      name: "AccQueueQuinary0",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinary0>;
    deployContract(
      name: "AccQueueQuinaryBlankSl",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinaryBlankSl>;
    deployContract(
      name: "AccQueueQuinaryMaci",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinaryMaci>;
    deployContract(
      name: "CommonUtilities",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CommonUtilities>;
    deployContract(
      name: "DomainObjs",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DomainObjs>;
    deployContract(
      name: "Utilities",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Utilities>;
    deployContract(
      name: "VkRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VkRegistry>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "IERC1155Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC1155Errors>;
    deployContract(
      name: "IERC20Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Errors>;
    deployContract(
      name: "IERC721Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Errors>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "SafeERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SafeERC20>;
    deployContract(
      name: "ERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC721>;
    deployContract(
      name: "IERC721Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Metadata>;
    deployContract(
      name: "IERC721",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721>;
    deployContract(
      name: "IERC721Receiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC721Receiver>;
    deployContract(
      name: "Address",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Address>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "Math",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Math>;
    deployContract(
      name: "Strings",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Strings>;
    deployContract(
      name: "HasherBenchmarks",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HasherBenchmarks>;
    deployContract(
      name: "Hasher",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Hasher>;
    deployContract(
      name: "MockVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockVerifier>;
    deployContract(
      name: "Pairing",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pairing>;
    deployContract(
      name: "PoseidonT3",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT3>;
    deployContract(
      name: "PoseidonT4",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT4>;
    deployContract(
      name: "PoseidonT5",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT5>;
    deployContract(
      name: "PoseidonT6",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PoseidonT6>;
    deployContract(
      name: "Verifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Verifier>;
    deployContract(
      name: "EASGatekeeper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.EASGatekeeper>;
    deployContract(
      name: "FreeForAllGatekeeper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FreeForAllGatekeeper>;
    deployContract(
      name: "HatsGatekeeperBase",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HatsGatekeeperBase>;
    deployContract(
      name: "HatsGatekeeperMultiple",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HatsGatekeeperMultiple>;
    deployContract(
      name: "HatsGatekeeperSingle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.HatsGatekeeperSingle>;
    deployContract(
      name: "SignUpGatekeeper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignUpGatekeeper>;
    deployContract(
      name: "SignUpTokenGatekeeper",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignUpTokenGatekeeper>;
    deployContract(
      name: "ConstantInitialVoiceCreditProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConstantInitialVoiceCreditProxy>;
    deployContract(
      name: "InitialVoiceCreditProxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.InitialVoiceCreditProxy>;
    deployContract(
      name: "IEAS",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IEAS>;
    deployContract(
      name: "IHats",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IHats>;
    deployContract(
      name: "IMACI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMACI>;
    deployContract(
      name: "IMessageProcessor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMessageProcessor>;
    deployContract(
      name: "IMessageProcessorFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMessageProcessorFactory>;
    deployContract(
      name: "IPoll",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPoll>;
    deployContract(
      name: "IPollFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPollFactory>;
    deployContract(
      name: "ITallyFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITallyFactory>;
    deployContract(
      name: "IVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVerifier>;
    deployContract(
      name: "IVkRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVkRegistry>;
    deployContract(
      name: "MACI",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MACI>;
    deployContract(
      name: "MessageProcessor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MessageProcessor>;
    deployContract(
      name: "MessageProcessorFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MessageProcessorFactory>;
    deployContract(
      name: "MockHatsProtocol",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockHatsProtocol>;
    deployContract(
      name: "Poll",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Poll>;
    deployContract(
      name: "PollFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PollFactory>;
    deployContract(
      name: "SignUpToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SignUpToken>;
    deployContract(
      name: "Tally",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Tally>;
    deployContract(
      name: "TallyFactory",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TallyFactory>;
    deployContract(
      name: "TopupCredit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TopupCredit>;
    deployContract(
      name: "AccQueue",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueue>;
    deployContract(
      name: "AccQueueBinary",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueBinary>;
    deployContract(
      name: "AccQueueBinary0",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueBinary0>;
    deployContract(
      name: "AccQueueBinaryMaci",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueBinaryMaci>;
    deployContract(
      name: "AccQueueQuinary",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinary>;
    deployContract(
      name: "AccQueueQuinary0",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinary0>;
    deployContract(
      name: "AccQueueQuinaryBlankSl",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinaryBlankSl>;
    deployContract(
      name: "AccQueueQuinaryMaci",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AccQueueQuinaryMaci>;
    deployContract(
      name: "CommonUtilities",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CommonUtilities>;
    deployContract(
      name: "DomainObjs",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DomainObjs>;
    deployContract(
      name: "Utilities",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Utilities>;
    deployContract(
      name: "VkRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.VkRegistry>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
