/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TallyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MESSAGE_DATA_LENGTH"
      | "genTallyVotesPackedVals"
      | "genTallyVotesPublicInputHash"
      | "hash2"
      | "hash3"
      | "hash4"
      | "hash5"
      | "hashLeftRight"
      | "isTallied"
      | "messageProcessor"
      | "mode"
      | "owner"
      | "poll"
      | "renounceOwnership"
      | "sbCommitment"
      | "sha256Hash"
      | "tallyBatchNum"
      | "tallyCommitment"
      | "tallyVotes"
      | "transferOwnership"
      | "updateSbCommitment"
      | "verifier"
      | "verifyPerVOSpentVoiceCredits"
      | "verifySpentVoiceCredits"
      | "verifyTallyProof"
      | "verifyTallyResult"
      | "vkRegistry"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

  encodeFunctionData(
    functionFragment: "MESSAGE_DATA_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "genTallyVotesPackedVals",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "genTallyVotesPublicInputHash",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hash2",
    values: [[BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "hash3",
    values: [[BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "hash4",
    values: [[BigNumberish, BigNumberish, BigNumberish, BigNumberish]]
  ): string;
  encodeFunctionData(
    functionFragment: "hash5",
    values: [
      [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hashLeftRight",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isTallied", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "messageProcessor",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mode", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "poll", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sbCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sha256Hash",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "tallyBatchNum",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tallyCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tallyVotes",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSbCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyPerVOSpentVoiceCredits",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish[][],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifySpentVoiceCredits",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTallyProof",
    values: [
      BigNumberish[],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyTallyResult",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish[][],
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "vkRegistry",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "MESSAGE_DATA_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genTallyVotesPackedVals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "genTallyVotesPublicInputHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hash2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hash3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hash4", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hash5", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hashLeftRight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isTallied", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageProcessor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "poll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sbCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sha256Hash", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tallyBatchNum",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tallyCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tallyVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSbCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyPerVOSpentVoiceCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifySpentVoiceCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTallyProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyTallyResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vkRegistry", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Tally extends BaseContract {
  connect(runner?: ContractRunner | null): Tally;
  waitForDeployment(): Promise<this>;

  interface: TallyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MESSAGE_DATA_LENGTH: TypedContractMethod<[], [bigint], "view">;

  genTallyVotesPackedVals: TypedContractMethod<
    [
      _numSignUps: BigNumberish,
      _batchStartIndex: BigNumberish,
      _tallyBatchSize: BigNumberish
    ],
    [bigint],
    "view"
  >;

  genTallyVotesPublicInputHash: TypedContractMethod<
    [
      _numSignUps: BigNumberish,
      _batchStartIndex: BigNumberish,
      _tallyBatchSize: BigNumberish,
      _newTallyCommitment: BigNumberish
    ],
    [bigint],
    "view"
  >;

  hash2: TypedContractMethod<
    [array: [BigNumberish, BigNumberish]],
    [bigint],
    "view"
  >;

  hash3: TypedContractMethod<
    [array: [BigNumberish, BigNumberish, BigNumberish]],
    [bigint],
    "view"
  >;

  hash4: TypedContractMethod<
    [array: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]],
    [bigint],
    "view"
  >;

  hash5: TypedContractMethod<
    [
      array: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ],
    [bigint],
    "view"
  >;

  hashLeftRight: TypedContractMethod<
    [left: BigNumberish, right: BigNumberish],
    [bigint],
    "view"
  >;

  isTallied: TypedContractMethod<[], [boolean], "view">;

  messageProcessor: TypedContractMethod<[], [string], "view">;

  mode: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  poll: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sbCommitment: TypedContractMethod<[], [bigint], "view">;

  sha256Hash: TypedContractMethod<[array: BigNumberish[]], [bigint], "view">;

  tallyBatchNum: TypedContractMethod<[], [bigint], "view">;

  tallyCommitment: TypedContractMethod<[], [bigint], "view">;

  tallyVotes: TypedContractMethod<
    [_newTallyCommitment: BigNumberish, _proof: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateSbCommitment: TypedContractMethod<[], [void], "nonpayable">;

  verifier: TypedContractMethod<[], [string], "view">;

  verifyPerVOSpentVoiceCredits: TypedContractMethod<
    [
      _voteOptionIndex: BigNumberish,
      _spent: BigNumberish,
      _spentProof: BigNumberish[][],
      _spentSalt: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _spentVoiceCreditsHash: BigNumberish,
      _resultCommitment: BigNumberish
    ],
    [boolean],
    "view"
  >;

  verifySpentVoiceCredits: TypedContractMethod<
    [
      _totalSpent: BigNumberish,
      _totalSpentSalt: BigNumberish,
      _resultCommitment: BigNumberish,
      _perVOSpentVoiceCreditsHash: BigNumberish
    ],
    [boolean],
    "view"
  >;

  verifyTallyProof: TypedContractMethod<
    [
      _proof: BigNumberish[],
      _numSignUps: BigNumberish,
      _batchStartIndex: BigNumberish,
      _tallyBatchSize: BigNumberish,
      _newTallyCommitment: BigNumberish
    ],
    [boolean],
    "view"
  >;

  verifyTallyResult: TypedContractMethod<
    [
      _voteOptionIndex: BigNumberish,
      _tallyResult: BigNumberish,
      _tallyResultProof: BigNumberish[][],
      _tallyResultSalt: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _spentVoiceCreditsHash: BigNumberish,
      _perVOSpentVoiceCreditsHash: BigNumberish
    ],
    [boolean],
    "view"
  >;

  vkRegistry: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MESSAGE_DATA_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "genTallyVotesPackedVals"
  ): TypedContractMethod<
    [
      _numSignUps: BigNumberish,
      _batchStartIndex: BigNumberish,
      _tallyBatchSize: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "genTallyVotesPublicInputHash"
  ): TypedContractMethod<
    [
      _numSignUps: BigNumberish,
      _batchStartIndex: BigNumberish,
      _tallyBatchSize: BigNumberish,
      _newTallyCommitment: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hash2"
  ): TypedContractMethod<
    [array: [BigNumberish, BigNumberish]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hash3"
  ): TypedContractMethod<
    [array: [BigNumberish, BigNumberish, BigNumberish]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hash4"
  ): TypedContractMethod<
    [array: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hash5"
  ): TypedContractMethod<
    [
      array: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashLeftRight"
  ): TypedContractMethod<
    [left: BigNumberish, right: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTallied"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "messageProcessor"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mode"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "poll"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sbCommitment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "sha256Hash"
  ): TypedContractMethod<[array: BigNumberish[]], [bigint], "view">;
  getFunction(
    nameOrSignature: "tallyBatchNum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tallyCommitment"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "tallyVotes"
  ): TypedContractMethod<
    [_newTallyCommitment: BigNumberish, _proof: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateSbCommitment"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyPerVOSpentVoiceCredits"
  ): TypedContractMethod<
    [
      _voteOptionIndex: BigNumberish,
      _spent: BigNumberish,
      _spentProof: BigNumberish[][],
      _spentSalt: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _spentVoiceCreditsHash: BigNumberish,
      _resultCommitment: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifySpentVoiceCredits"
  ): TypedContractMethod<
    [
      _totalSpent: BigNumberish,
      _totalSpentSalt: BigNumberish,
      _resultCommitment: BigNumberish,
      _perVOSpentVoiceCreditsHash: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyTallyProof"
  ): TypedContractMethod<
    [
      _proof: BigNumberish[],
      _numSignUps: BigNumberish,
      _batchStartIndex: BigNumberish,
      _tallyBatchSize: BigNumberish,
      _newTallyCommitment: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyTallyResult"
  ): TypedContractMethod<
    [
      _voteOptionIndex: BigNumberish,
      _tallyResult: BigNumberish,
      _tallyResultProof: BigNumberish[][],
      _tallyResultSalt: BigNumberish,
      _voteOptionTreeDepth: BigNumberish,
      _spentVoiceCreditsHash: BigNumberish,
      _perVOSpentVoiceCreditsHash: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "vkRegistry"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
