/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMessageProcessor,
  IMessageProcessorInterface,
} from "../../../contracts/interfaces/IMessageProcessor";

const _abi = [
  {
    inputs: [],
    name: "processingComplete",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "sbCommitment",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMessageProcessor__factory {
  static readonly abi = _abi;
  static createInterface(): IMessageProcessorInterface {
    return new Interface(_abi) as IMessageProcessorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMessageProcessor {
    return new Contract(address, _abi, runner) as unknown as IMessageProcessor;
  }
}
